function decoratorFactory(name: string) {
    // Return a decorator function that takes a constructor function as input and logs the name parameter to the console
    return (constructor: Function) => {
      console.log(`decorator function called with : ${name}`);
    }
  }
// Apply the decorator generated by decoratorFactory function to the ClassWithDecoratorFactory class
@decoratorFactory('testName')
class ClassWithDecoratorFactory {
}
  